##
## EPITECH PROJECT, 2021
##
## File description:
## Makefile
##

NAME	=       miniProgExec

NAME_T	=		unitTests

MAIN    =       main.py


all: $(MAIN)
		cp $(MAIN) $(NAME)
		chmod 755 $(NAME)

tests_run:

clean:
		rm -f $(NAME)

fclean: 
		rm -f $(NAME)

re: fclean all